"""initial schema

Revision ID: 27a03072965a
Revises: 
Create Date: 2026-05-25 21:22:57.665087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a03072965a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graphs_user_id'), 'graphs', ['user_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('graph_id', sa.String(), nullable=False),
    sa.Column('heading', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('input_prompt', sa.Text(), nullable=False),
    sa.Column('ai_output', sa.Text(), nullable=False),
    sa.Column('edge_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('trunk', 'side', 'prereq')", name='ck_nodes_kind'),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_graph_id'), 'nodes', ['graph_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('graph_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("edge_type IN ('subtopic', 'prerequisite', 'see-also', 'side-question')", name='ck_edges_edge_type'),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'edge_type', name='uq_edges_src_tgt_type')
    )
    op.create_index(op.f('ix_edges_graph_id'), 'edges', ['graph_id'], unique=False)
    op.create_index(op.f('ix_edges_source_id'), 'edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_edges_target_id'), 'edges', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edges_target_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_source_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_graph_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_nodes_graph_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_graphs_user_id'), table_name='graphs')
    op.drop_table('graphs')
    # ### end Alembic commands ###
